<expressionPrecedenceLevel_0> ::= <expressionPrecedenceLevel_0> "+" <expressionPrecedenceLevel_1>
                               |  <expressionPrecedenceLevel_0> "-" <expressionPrecedenceLevel_1>
                               |  <expressionPrecedenceLevel_1>

<expressionPrecedenceLevel_1> ::= <expressionPrecedenceLevel_1> "*" <expressionPrecedenceLevel_2>
                               |  <expressionPrecedenceLevel_1> "/" <expressionPrecedenceLevel_2>
                               |  <expressionPrecedenceLevel_2>

<expressionPrecedenceLevel_2> ::= <unaryExpression>

<unaryExpression> ::= "+" <unaryExpression>
                    |  "-" <unaryExpression>
                    |  <primaryExpression>

<primaryExpression> ::= "(" <expressionPrecedenceLevel_0> ")"
                      |  <number>
                      |  <variable>

<number> ::= <digit>+

<digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

<variable> ::= <capitalLetter> <variableTail>*

<variableTail> ::= <letter> | <digit>

<capitalLetter> ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"

<letter> ::= <capitalLetter> | <smallLetter>

<smallLetter> ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"








