# LIMIT_OF_SYMBOLS_LENGTH_IN_VALIDATION 4

<pid> ::= "<" <integer> "." <integer> "." <integer> ">"


<number> ::= <integer> | <float>
<integer> ::= <digit> <numberTail>
<float> ::= <digit> <numberTail> "." <digit> <numberTail>

<numberTail> ::= <digit> <numberTail>
               | <empty>


<string> ::= <stringQuoteOne> | <stringInSigil>
<stringQuoteOne> ::= "\"" <stringQuoteOneTail> "\""
<stringQuoteOneTail> ::=  <anyUnicodeCharsExceptNonEscapedDoubleQuote> | <empty>


##########################################################################################
<stringInSigil> ::= "\"\"\"" <stringSigilTail> "\"\"\""

<stringSigilTail> ::= <sigilSafeChar> <stringSigilTail>
                   | <empty>

<sigilSafeChar> ::= <anyUnicodeCharsExceptNonEscapedDoubleQuote>
             | "\"" <sig_anyCharExceptQuoteOrEmpty>
             | "\"" "\"" <sig_anyCharExceptQuoteOrEmpty>

<sig_anyCharExceptQuoteOrEmpty> ::= <anyUnicodeCharsExceptNonEscapedDoubleQuote>
                              | <empty>

##########################################################################################



<atom> ::= <atomInQuotes> | <atomSmallFirstChar>
<atomSmallFirstChar> ::= <letterSmall> <atomSmallFirstChar_tail>
<atomSmallFirstChar_tail> ::= <atomPossibleCharAfterFirstPosition> <atomSmallFirstChar_tail>
                            | <empty>
<atomPossibleCharAfterFirstPosition> ::= <letter>
                                      | <digit>
                                      | "_" | "@"


<atomInQuotes> ::= "'" <atomCharList_inQuotes> "'"
<atomCharList_inQuotes> ::= <anyUnicodeCharsExceptNonEscapedSingleQuote> <atomCharList_inQuotes>
                          | <empty>






#### LOCAL SYMBOLS to generate possible usecases, DON'T MERGE THEM - use short, simple definitions ##########

<anyUnicodeCharsExceptNonEscapedSingleQuote> ::=  "k" | "l" | "\t"
<anyUnicodeCharsExceptNonEscapedDoubleQuote> ::= "o" | "p"

<letter> ::= "t" | "m"
<digit>  ::= "1" | "2"
<empty>  ::=
<letterSmall> ::= "e" | "f"